name: jq output
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  jq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: jq verseion
        run: jq --version
      - name: jq basic
        run: bash ./jq_basic.sh
      - name: jq array
        run: bash ./jq_array.sh
      - name: jq date
        run: bash ./jq_date.sh
      - name: jq functions
        run: bash ./jq_functions.sh
      - name: jq operator
        run: bash ./jq_operator.sh
